
trigger:

- master

pool:
  vmImage: ubuntu-latest


variables:
 
  IMAGE_TAG: latest

steps:

-
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'


   
    


