
trigger:

- master

pool:
  vmImage: ubuntu-latest


variables:
 
  IMAGE_TAG: latest

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'devops'
    scannerMode: 'MSBuild'
    projectKey: 'sonar.cpd.cross_project'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: SonarQubeAnalyze@5   


- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
