

trigger:

- master

pool:
  vmImage: ubuntu-latest

variables:
 
  IMAGE_TAG: latest

steps:

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: docker compose build ordering.api 
    


