

trigger:

- master

pool:
  vmImage: ubuntu-latest


variables:
 
  IMAGE_TAG: latest

steps:
- task: DockerCompose@0
  displayName: 'Build Ordering API image'
  inputs:
    containerregistrytype: 'Container Registry'
    command: 'build'
    dockerComposeFile: '**/docker-compose.yml'
    projectName: 'myProjectName'
    arguments: 'ordering.api'
    


