
trigger:

- master

pool:
  vmImage: ubuntu-latest


variables:
 
  IMAGE_TAG: latest

steps:

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqubeServer'
    scannerMode: 'MSBuild'
    projectKey: 'pfa_pfa_AYfYhOmun44-h-8FJYUe'
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'src/ApiGateways/OcelotApiGw/Dockerfile'

    
- task: SonarQubeAnalyze@5
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'

   
    


